CREATE DATABASE IF NOT EXISTS CrashesDB;

USE CrashesDB;

CREATE TABLE IF NOT EXISTS crashes (
    DATE VARCHAR(11), 
    TIME VARCHAR(5), 
    BOROUGH VARCHAR(13), 
    ZIP_CODE VARCHAR(5), 
    LATITUDE VARCHAR(30),
    LONGITUDE VARCHAR(30),
    LOCATION VARCHAR(30), 
    ON_STREET_NAME VARCHAR(30),
    CROSS_STREET_NAME VARCHAR(30),
    OFF_STREET_NAME VARCHAR(30),
    NUM_PERSONS_INJURED INT(2),
    NUM_PERSONS_KILLED INT(2),
    NUM_PEDESTRIANS_INJURED INT(2),
    NUM_PEDESTRIANS_KILLED INT(2),
    NUM_CYCLISTS_INJURED INT(2),
    NUM_CYCLISTS_KILLED INT(2),
    NUM_MOTORISTS_INJURED INT(2),
    NUM_MOTORISTS_KILLED INT(2),
    CONTRIBUTING_FACTOR_1 VARCHAR(30),
    CONTRIBUTING_FACTOR_2 VARCHAR(30),
    CONTRIBUTING_FACTOR_3 VARCHAR(30),
    CONTRIBUTING_FACTOR_4 VARCHAR(30),
    CONTRIBUTING_FACTOR_5 VARCHAR(30),
    UNIQUE_KEY INT(7),
    VEHICLE_TYPE_1 VARCHAR(30),
    VEHICLE_TYPE_2 VARCHAR(30),
    VEHICLE_TYPE_3 VARCHAR(30),
    VEHICLE_TYPE_4 VARCHAR(30),
    VEHICLE_TYPE_5 VARCHAR(30),
    PRIMARY KEY(UNIQUE_KEY)
);

LOAD DATA LOCAL INFILE 'C:/Users/John/Downloads/NYPD_Motor_Vehicle_Collisions.csv'
INTO TABLE crashes
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

DELETE FROM crashes WHERE LONGITUDE = '';

CREATE TABLE IF NOT EXISTS Crashes_Staten_Island (
    SELECT * FROM crashes WHERE BOROUGH = "Staten Island"
);

CREATE TABLE IF NOT EXISTS Crashes_Brooklyn (
    SELECT * FROM crashes WHERE BOROUGH = "Brooklyn"
);

CREATE TABLE IF NOT EXISTS Crashes_Bronx (
    SELECT * FROM crashes WHERE BOROUGH = "Bronx"
);

CREATE TABLE IF NOT EXISTS Crashes_Queens (
    SELECT * FROM crashes WHERE BOROUGH = "Queens"
);

CREATE TABLE IF NOT EXISTS Crashes_Manhattan (
    SELECT * FROM crashes WHERE BOROUGH = "Manhattan"
);